* YouTube-Filter
Most YouTube Videos have keywords. If they are allowed, all is fine. Else, blocks with a page displaying the keywords.

** Status

*currently withdrawn from Chrome Web Store due to Youtube copyright claim (icon)*

[[https://addons.mozilla.org/de/firefox/addon/youtube-filter/][https://img.shields.io/amo/v/youtube-filter.svg]]
[[https://chrome.google.com/webstore/detail/jsguardian/dcnjfkkecmhafmahafoemckgfbcpkfag][https://img.shields.io/chrome-web-store/v/dcnjfkkecmhafmahafoemckgfbcpkfag.svg]]

** Versions
*** 0.7.2: Youtube forbid previous icon
*** 0.7.1: Code was less polished
*** 0.7.0: Lacked blacklist
*** 0.6.3
**** Failed in multiple ways
     - on new tab
     - at beginning on same page
*** 0.6.2
**** Was not working on Chrome / with new YouTube design
*** 0.5.2
**** Failed
     on youtube front page
*** 0.5.1
**** Had
     unclean code that used =innerHTML= (thanks to Mozilla automated review)
*** 0.5.0
**** Lacked
     - support for Chromium due to old API
*** 0.4.2
**** Fixed
     - block page showed non-english tags wrongly
*** 0.4.1
**** Fixed
     Double-click started full-screen (see [[0.4.0]] for the problem)
*** 0.4.0
**** Added/Fixed
     Fullscreen mode did not trigger keyword block, as it did not
     update keywords, so its button was made invisible.
**** Fixed
     There was no easy way to go back to before the blocked page.
*** 0.3.2
**** Fixed
     broke pages with embedded videos
*** 0.3.1
**** Fixed
     had allowed another way to play videos without keywords
*** 0.3.0
**** Fixed
     Played videos without keywords
*** 0.2.1
**** Fixed
     lacked multiprocess + private browsing flags
*** 0.2.0
**** Added
     Lacked blacklist
*** 0.1
**** Fixed
     did not handle ~keywords = ''~ correctly

** Credits
   - reduced jquery by http://projects.jga.me/jquery-builder/
     - recreated at
   https://raw.githubusercontent.com/jgallen23/jquery-builder/0.7.0/dist/2.1.1/jquery-css-deprecated-dimensions-effects-event-alias-offset-sizzle-wrap.min.js
